/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'
import { Route as InvitationsTokenRouteImport } from './routes/invitations.$token'
import { Route as TripTripIdSettlementRouteImport } from './routes/trip.$tripId.settlement'
import { Route as TripTripIdNewRecordRouteImport } from './routes/trip.$tripId.new-record'
import { Route as TripTripIdManageRouteImport } from './routes/trip.$tripId.manage'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdSettlementRoute = TripTripIdSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => TripTripIdRoute,
} as any)
const TripTripIdNewRecordRoute = TripTripIdNewRecordRouteImport.update({
  id: '/new-record',
  path: '/new-record',
  getParentRoute: () => TripTripIdRoute,
} as any)
const TripTripIdManageRoute = TripTripIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => TripTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/trip/$tripId': typeof TripTripIdRouteWithChildren
  '/trip/$tripId/manage': typeof TripTripIdManageRoute
  '/trip/$tripId/new-record': typeof TripTripIdNewRecordRoute
  '/trip/$tripId/settlement': typeof TripTripIdSettlementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/trip/$tripId': typeof TripTripIdRouteWithChildren
  '/trip/$tripId/manage': typeof TripTripIdManageRoute
  '/trip/$tripId/new-record': typeof TripTripIdNewRecordRoute
  '/trip/$tripId/settlement': typeof TripTripIdSettlementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/trip/$tripId': typeof TripTripIdRouteWithChildren
  '/trip/$tripId/manage': typeof TripTripIdManageRoute
  '/trip/$tripId/new-record': typeof TripTripIdNewRecordRoute
  '/trip/$tripId/settlement': typeof TripTripIdSettlementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trips'
    | '/invitations/$token'
    | '/trip/$tripId'
    | '/trip/$tripId/manage'
    | '/trip/$tripId/new-record'
    | '/trip/$tripId/settlement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trips'
    | '/invitations/$token'
    | '/trip/$tripId'
    | '/trip/$tripId/manage'
    | '/trip/$tripId/new-record'
    | '/trip/$tripId/settlement'
  id:
    | '__root__'
    | '/'
    | '/trips'
    | '/invitations/$token'
    | '/trip/$tripId'
    | '/trip/$tripId/manage'
    | '/trip/$tripId/new-record'
    | '/trip/$tripId/settlement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripsRoute: typeof TripsRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  TripTripIdRoute: typeof TripTripIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/settlement': {
      id: '/trip/$tripId/settlement'
      path: '/settlement'
      fullPath: '/trip/$tripId/settlement'
      preLoaderRoute: typeof TripTripIdSettlementRouteImport
      parentRoute: typeof TripTripIdRoute
    }
    '/trip/$tripId/new-record': {
      id: '/trip/$tripId/new-record'
      path: '/new-record'
      fullPath: '/trip/$tripId/new-record'
      preLoaderRoute: typeof TripTripIdNewRecordRouteImport
      parentRoute: typeof TripTripIdRoute
    }
    '/trip/$tripId/manage': {
      id: '/trip/$tripId/manage'
      path: '/manage'
      fullPath: '/trip/$tripId/manage'
      preLoaderRoute: typeof TripTripIdManageRouteImport
      parentRoute: typeof TripTripIdRoute
    }
  }
}

interface TripTripIdRouteChildren {
  TripTripIdManageRoute: typeof TripTripIdManageRoute
  TripTripIdNewRecordRoute: typeof TripTripIdNewRecordRoute
  TripTripIdSettlementRoute: typeof TripTripIdSettlementRoute
}

const TripTripIdRouteChildren: TripTripIdRouteChildren = {
  TripTripIdManageRoute: TripTripIdManageRoute,
  TripTripIdNewRecordRoute: TripTripIdNewRecordRoute,
  TripTripIdSettlementRoute: TripTripIdSettlementRoute,
}

const TripTripIdRouteWithChildren = TripTripIdRoute._addFileChildren(
  TripTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripsRoute: TripsRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  TripTripIdRoute: TripTripIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
